database:
  username: yaninyzwitty
  host: vague-echidna-13927.j77.aws-eu-central-1.cockroachlabs.cloud
  database: defaultdb
  port: 26257
  sslmode: verify-full
  password: testpassword
server:
  debug: true
  gateway_port: 8080
  product_service_port: 50051
  otlpGrpcEndpoint: 4317
  otlpHttpEndpoint: 4318
  prom_http_addr: 8081
