name: Docker Build and Push

on:
  push:
  pull_request:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      product-service: ${{ steps.changes.outputs.product-service }}
      gateway-service: ${{ steps.changes.outputs.gateway-service }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            product-service:
              - 'packages/product-service/**'
              - 'packages/shared/**'
            gateway-service:
              - 'packages/gateway-service/**'
              - 'packages/shared/**'

  build-product:
    needs: changes
    if: ${{ needs.changes.outputs.product-service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./packages/product-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/product-service:latest

  build-gateway:
    needs: changes
    if: ${{ needs.changes.outputs.gateway-service == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: ./packages/gateway-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/gateway-service:latest
